### PR TITLE
New disaggregation algorithm: Maximum likelihood estimation

### PR DESCRIPTION
**Pull request by josemao**
Maximum likelihood estimation algorithm for disaggregating a single appliance

### CODE REVIEW

**Comment by JackKelly** [comment]
Excellent work, thank you!  And welcome to the wonderful world of NILMTK development :)

The code looks good.  Before we merge, please could you address some of [the 'problems' identified by landscape](https://landscape.io/diff/173350)?  These are all just minor issues but it's always nice to have code which conforms to as many of these Python 'best practice' rules as possible.

**Comment by josemao** [comment]
Hi,

Thank you!!

I'll fix those problems as soon as possible :)

cheers,

José M. Alcalá Orzáez

2015-06-09 15:42 GMT+02:00 Jack Kelly <notifications@github.com>:

**Comment by oliparson** [comment]
@josemao have you had a chance to look at addressing the problems identified by landscape?

**Comment by josemao** [comment]
Hi,

I´ve been very busy with deadlines and did not have the time to address the
problems. It will be the first thing to do for next monday. Sorry for that.

José,

José M. Alcalá Orzáez

2015-06-19 17:07 GMT+02:00 Oliver Parson <notifications@github.com>:

**Comment by JackKelly** [comment]
great work, thank you @josemao 

@oliparson or @nipunreddevil would either of you guys have time to review @josemao's new code and either merge it (manually) or suggest further tweaks if appropriate?  This week is a little busy for me...

**Comment by oliparson** [comment]
I'll have some time on Friday to look into this, though feel free to take a look sooner @nipunreddevil if you like.

**Comment by josemao** [comment]
Hi,

Sorry guys, I did a commit with some changes but still need to do more.
Hope to finish today and I let you know when it is ready for review.

José M. Alcalá Orzáez

2015-06-23 14:06 GMT+02:00 Oliver Parson <notifications@github.com>:

**Comment by JackKelly** [comment]
thanks, @oliparson 

thanks loads for the update @josemao; great work!

**Comment by josemao** [comment]
Hi, 

I'm trying to add a commit to the pull request but it says: " remote: Permission to nilmtk/nilmtk.git denied to josemao." 

Any idea about that?

**Comment by JackKelly** [comment]
> I'm trying to add a commit to the pull request but it says: " remote: Permission to nilmtk/nilmtk.git denied to josemao."

you need to push your commit to your own fork of nilmtk.  i.e. something like `josemao/nilmtk`

**Comment by josemao** [comment]
Hi, 
I think the code is ready now. I cleaned most of the suggestions from landscape. There are still some highlighted line I think they should not be changed tough. 

Please, let me know if it still needs more polishing. 

Cheers,

**Comment by nipunreddevil** [comment]
@josemao : Looks good now. Somehow, we can't do an auto merge now. Did you pull the latest nilmtk commits? I guess once you've done that we should be able to do an auto merge from within github.

**Comment by josemao** [comment]
Hi @nipunreddevil, 

Done! Now, you should be able to merge.

**Comment by JackKelly** [comment]
sorry, please can you pull again, @josemao?  I just fixed a bug in some code I wrote which was preventing our unittests from passing!

Once you've pulled, merged, committed and pushed again then we can see if Travis is happy with your code  too :)

**Comment by josemao** [comment]
Hi @JackKelly. Already done that. Let's see now :)

**Comment by nipunreddevil** [comment]
Thanks @josemao: I am waiting for the TravisCI and then will merge it.

**Comment by nipunreddevil** [comment]
Merged @josemao . Great work. Looking forward to demo code for the algorithm :)

**Comment by JackKelly** [comment]
great work everyone, thank you :)

**Comment by josemao** [comment]
Great :)) 

I also included a notebook on https://github.com/nilmtk/nilmtk/blob/master/notebooks/experimental/mle.ipyn

I still need to do some more work on the final disaggregation tough.

**Pull request merged**
