### PR TITLE
Added latent Bayesian melding disaggregation method

### PR DESCRIPTION
**Pull request by MingjunZhong**
I added latent Bayesian melding disaggregation method to NILMTK. I also added a test method, which produces nothing, but only is checking if the code is working. (It works in my computer anyway; remember it requires the MOSEK solver.) The code in the test method is easy to be used to produce a demo file, which can produce some plots to compare ground truth appliance readings and the inferred ones, but I have not found any demo files in NILMTK. Note that I am only using disaggregation_chunk to disaggregate a chunk; this looks easier to be understood. Any questions please let me know.

### CODE REVIEW

**Comment by MingjunZhong** [comment]
It looks the error comes from importing the MOSEK module.

**Comment by nipunbatra** [comment]
Hi @MingjunZhong 
Thanks for the PR. The error is indeed due to importing MOSEK. 
What's the easiest way to install the dependencies in your code? If that's trivial, we could just add an extra line in the CI code.

**Comment by MingjunZhong** [comment]
@nipunbatra It is easy to use MOSEK, but it requires license which is free, and everyone has to do independently. I suggest to direct to MOSEK websites: for installing mosek, https://mosek.com/resources/downloads/faq/howto-install-license; for license, https://www.mosek.com/resources/academic-license.

**Comment by JackKelly** [comment]
@MingjunZhong thank you so much for doing this work!  Great stuff!

I think the challenge that we have is that MOSEK might not let us use their software on our continuous integration server.  And all users of NILMTK (even ones with little interest in running all disag algorithms) would also need to get a MOSEK license.  I think this is a great opportunity to discus *where* cutting edge NILM algorithms like LBM should live.  I've started a new issue to discuss this issue: #466  

Please feel free to dive into that issue with any comments!  Once we conclude that discussion then we can decide where LBM should live.

**Comment by MingjunZhong** [comment]
@JackKelly Thanks for the comments. Yes it is a problem if you integrate LBM into NILMTK, which then also needs the MOSEK solver. 
One option is that: all NILM algorithms, which do not require dependencies, live in NILMTK; uses have to install by themselves other algorithms which require dependencies. This looks like option 2) in #466

**Comment by nipunbatra** [comment]
Hi @MingjunZhong : Is the `train` method coded separately?

**Comment by MingjunZhong** [comment]
@nipunbatra : Yes, all the HMM parameters were trained using HES data, and as well as the parameters in the population models; I then used them as known values.

**Comment by nipunbatra** [comment]
@MingjunZhong : So, I was wondering if you will also provide the code for training, or, only the JSON corresponding to the trained model.

**Comment by MingjunZhong** [comment]
@nipunbatra Good suggestion. I can have the code for training HMM parameters, but for the population models, the users could define them empirically by using data or doing experiments.

**Comment by nipunbatra** [comment]
@MingjunZhong : It would be good if the sample period is defined in a better way, maybe at runtime? rather than hardcoding it?

**Comment by MingjunZhong** [comment]
I have added the relaxed fhmm class to the disaggregation directory - the code is also using the solver.

**Comment by JackKelly** [comment]
@MingjunZhong great work!  Thank you!

@nipunbatra remind me: what was our conclusion regarding where these algorithms should live?  did we decide that cutting edge should live in the author's github repository and we'd keep a wiki page linking to cutting edge algorithms?

**Comment by JackKelly** [comment]
I've started a wiki page for listing NILM algorithms which work with NILMTK: https://github.com/nilmtk/nilmtk/wiki/NILM-Algorithms

**Comment by oliparson** [comment]
@JackKelly Nice work on the NILM algorithms wiki page. Should we link to it from the NILMTK github readme or the documentation page?

**Comment by JackKelly** [comment]
> Should we link to it from the NILMTK github readme or the documentation page?

yes, good idea!  I'm just about to go on holiday though so please can someone else do it?...

**Comment by oliparson** [comment]
Done! e104401

**Comment by JackKelly** [comment]
nice, thanks!

**Comment by PMeira** [comment]
Closing per #466

**Pull request closed without merging**
