### PR TITLE
Updated results.py to replace deprecated dataframe.append in pandas

### PR DESCRIPTION
**Pull request by prince7003**
File: results.py
	Issue_description: line77 , line108 : AttributeError: 'DataFrame' object has no attribute 'append'
	Findings: pandas.DataFrame.append is deprecated since version 1.4.0 . append is replace with concat() .
	Resolution: have make use of concat instead of append
	Result: Susscessful
        Link: https://pandas.pydata.org/pandas-docs/version/1.4/reference/api/pandas.DataFrame.append.html

       SS: 
image

### CODE REVIEW

**Comment by levaphenyl** [comment]
Thank you for contributing!
1. I just merged your other PR on `goodsections.py`. Please rebase to exclude the previous commit from this PR.
2. You could improve your commits by being as specific as in the title. For instance: `Update elecmeter` --> `fix(elecmeter): use lists because ac_types is a generator.`
3. You are making changes based seemingly on a recent version of pandas. However, [`setup.py`](https://github.com/nilmtk/nilmtk/blob/master/setup.py#L98) instructs that pandas version is 0.25.3 for this project. I agree that it is too old and should be updated. Could you update the setup file with your library versions in this PR, please?
4. Please run the tests and confirm that you don't break anything.

@PMeira, @nipunbatra - Please shout if I am wrong! :upside_down_face:

**Comment by prince7003** [comment]
Hi , 
Sure let me do the required changes

**Comment by prince7003** [comment]
@levaphenyl , I am facing issue with rebasing can i close this PR and again raise new PR with required changes?

**Comment by levaphenyl** [comment]
@prince7003 - Yes, if it is easier for you.

My two cents on git: it seems that you have merged master with your branch and ended up in a deadlock. To avoid that, you could follow these steps in the console:
1. revert your merge commit (https://stackoverflow.com/q/927358/8289769),
2. `git fetch -ap` to fetch progress in all branches,
3. `git log --all --graph --decorate --oneline` to see the commit tree. Copy the ID of the last commit in the main branch. It should be `684dffd`.
4. `git rebase -a -i 684dffd` to interactively rebase from the last commit in the main branch.

**Pull request closed without merging**
