### PR TITLE
Updated couple of deprecated functionalities

### PR DESCRIPTION
**Pull request by prince7003**
1th Issue:
    
	File: /disaggregate/hart_85.py , line 529, 565 many places it is written
	Issue_description: AttributeError: 'DataFrame' object has no attribute 'ix'
	Findings: Starting in 0.20.0, the .ix indexer is deprecated, in favor of the more strict .iloc and .loc indexers.
	Link: https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.ix.html
	Resolution: Have using .loc instead of .ix because in the code indexing is str(columns name)

2th Issue:

    File: generate_data.py, line 26
	Issue_description: python inbuilt timedelta class does not takes seconds value as np.int32.(line 26), 
	Resolution: converted numpy array to list.
	
	
	
3th Issue:
    
	File: generate_data.py , line 89
	Issue_description:  'float' object cannot be interpreted as an integer(line 89).
	Resolution: converted float variable to int.
	
4th Issue:

     File: "E:\Computer_Science\Machine_Learning\nilmtk_test\nilmtk\datastore\hdfdatastore.py", line 169, in put
     Issue_description: TypeError: HDFStore.put() got an unexpected keyword argument 'expectedrows'
	 Resolution: Removed the keyword 'expectedrows'

Below is my system configuration for different library , i am changing it accordingly

image

### CODE REVIEW

**Comment by prince7003** [comment]
Hi, @PMeira , @levaphenyl , can you please review the PR , I have made the exact changes you proposed.

**Comment by levaphenyl** [comment]
Great, thank you @prince7003 :).
Your first commit has just been merged into the main branch. Can you rebase your PR to remove it, please?
What versions of `numpy`, and `pandas` do you use, please?
Please update [the package requirements](https://github.com/nilmtk/nilmtk/blob/master/setup.py#L98) as a new commit in this PR.

**Comment by prince7003** [comment]
Hi @levaphenyl  ,  I am using the latest versions of both , i will update the requirements. Thank you

**Comment by prince7003** [comment]
Hi @levaphenyl , I have done rebasing to remove the last merged commit

**Comment by levaphenyl** [comment]
Thank you! It looks good to me.
Have you tested your new code by running [`nosetests`](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/contributing.md#contribute-code-or-documentation)?

**Comment by prince7003** [comment]
Hi @levaphenyl  , i have tested the code , using unittest in the tests folder , every test is running fine

**Pull request merged**
