### PR TITLE
Added install IPython step

### PR DESCRIPTION
**Pull request by pauldeng**
IPython is required and it was not in the installation guide.

OS: Xubuntu 14.04.1

### CODE REVIEW

**Comment by nipunreddevil** [comment]
Thanks for the PR. 
Isn't IPython included as a part of Anaconda? I think it is.

**Comment by pauldeng** [comment]
You are right.

I realize I am using Miniconda which is much smaller than standard Anaconda. IPython is not included in Miniconda. Sorry.

**Comment by nipunreddevil** [comment]
No worries. You could also do `conda install ipython` after installing miniconda.

**Comment by pauldeng** [comment]
Yes, thanks a lot.

**Pull request closed without merging**
