### PR TITLE
Added DEDDIAG converter

### PR DESCRIPTION
**Pull request by nastya-oh**
This is a converter for a new dataset DEDDIAG ([Scientific Publication](https://doi.org/10.1038/s41597-021-00963-2)  and [Dataset Download](https://doi.org/10.6084/m9.figshare.13615073) ).  
Please see the readme-file to know how to use the converter and how to import data into NILMTK.

### CODE REVIEW

**Comment by nipunbatra** [comment]
Thanks a lot for this PR and for the dataset!

**Comment by LqzViva** [comment]
@nastya-oh @hort90,Hello, I don’t know how to use the import.sh file. Could you tell me how to use the import.sh file to import the dataset into the database？

**Comment by nastya-oh** [comment]
Hello @LqzViva, if your docker container is running, you can import data into it. Firstly you need a Linux machine or wsl, if you're Windows user. Make sure, that this file is executable. If it's not, you can run `chmod u+x import.sh` in Linux command line (in the dir of this file). Then you can import data with the following command: `./import.sh`

**Comment by LqzViva** [comment]
> Hello @LqzViva, if your docker container is running, you can import data into it. Firstly you need a Linux machine or wsl, if you're Windows user. Make sure, that this file is executable. If it's not, you can run `chmod u+x import.sh` in Linux command line (in the dir of this file). Then you can import data with the following command: `./import.sh`

@nastya-oh Thank you for your reply. I downloaded wsl and can now import the data set into the database. This is of great help to me. Thanks again for your reply

**Comment by camilomarino** [comment]
I am interested in accessing all houses with NILMTK and not just house 8. Is there a way to convert all houses to .h5?

**Comment by nastya-oh** [comment]
Hi @camilomarino ,
Sorry for late answer. How to convert the weight dataset, I described in this [comment](https://github.com/nilmtk/nilmtk/pull/936#commitcomment-71191584)

**Pull request merged**
