### PR TITLE
Compatibility to recent versions of the dependencies

### PR DESCRIPTION
**Pull request by PMeira**
This PR should address #629 

All tests work on both Python 3.6 and 2.7, with one exception: `test_wiring_graph` was updated to match the results when running on Python 3.6, so it should fail on 2.7 -- I didn't find it important enough to justify a conditional test.

### CODE REVIEW

**Comment by oliparson** [comment]
Hi @PMeira, thanks so much for this PR and sorry for taking so long getting round to responding. The [NILMTK installation docs](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_dev.md) currently recommend python 2.7 rather than python 3 - do you think we should start recommending python 3 with these changes?

**Comment by PMeira** [comment]
Hi @oliparson,
In general, I think recommending Python 3 should be OK now, since most modules have either been ported to Python 3 or moved completely (dropping 2.7). Most courses and books seem to use 3+ too, so the academic world is probably using more Python 3 in general. 

NILMTK doesn't require either version by itself as it doesn't use any fancy new Python feature and `six` is already being used where necessary. On the long run though, some dependencies will drop support for Python 2.7, NumPy is a big one:

> Starting on **January 1, 2019**, any new feature releases will support only Python3.

Personally, a year ago I evaluated all modules we use in my research group and the only ones that didn't support Python 3 at all were abandoned years ago (I found alternatives for those). We effectively moved everything to Python 3.6 a couple of months ago.

We could leave this open for some days and try to poll the devs and users but I'm not sure what's the best approach for that, if even feasible. Any ideas?

About `test_wiring_graph`: I can add that conditional  to make sure all tests still pass on Python 2.7 -- I'm pretty the result changes on this test are due to the different dict implementations between 2.7 and 3.6, which results in different key order.

Independent of the 2/3 issue, I should have updated the docs before opening the PR, sorry about that! I'll wait on a final word on the Python version and then reflect all changes on the docs, making sure the all recommended steps work as expected with the updated dependencies.

**Comment by oliparson** [comment]
Hi, 

Thanks again for your detailed response. I completely agree that we should be moving towards python 3. I was more asking whether you thought NILMTK was at a stage where we can start _recommending_ python 3, and it sounds like we are!

If you're happy to update test_wiring_graph and the readme and submit a new PR I'm very happy to push the merge button :)

Cheers,

**Comment by nipunbatra** [comment]
I'd be in favor of only supporting Python 3 too!

**Comment by lhx20070322** [comment]
HI @PMeira, 
   Can  I  install nilmtk on python3.6 at win10， now？

**Comment by PMeira** [comment]
Sorry for the delay, I should finish the changes this weekend.

@lhx20070322 You can install from my repository, move specifically with the [environment.yml that points to it](https://github.com/PMeira/nilmtk/blob/192ce053d3b4253cc0fa1e07b5cbf3c7c4c156d3/environment.yml) if you're using conda. If you find any issues, please let me know.

**Comment by lhx20070322** [comment]
HI @PMeira,
     There are a lot of ImportWarning when Irun nosetest(win10 64bit). 
$ nosetests
C:\Users\hhy\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
C:\Users\hhy\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
C:\Users\hhy\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
C:\Users\hhy\nilmtk\nilmtk\dataset_converters\redd\convert_redd.py:109: DeprecationWarning: invalid escape sequence \d
  return _matching_ints(dir_names, '^house_(\d)$')
C:\Users\hhy\nilmtk\nilmtk\dataset_converters\redd\convert_redd.py:120: DeprecationWarning: invalid escape sequence \d
  return _matching_ints(filenames, '^channel_(\d\d?).dat$')
............................................Closing remaining open files:C:\Users\hhy\nilmtk\data\energy.h5...done

----------------------------------------------------------------------
Ran 44 tests in 45.432s

OK

**Comment by lhx20070322** [comment]
when I run  /nilmtk/docs/manual/user_guide/loading_data_into_memory.ipynb.I got the following erro.
df = fridge.load()
next(df)
df.head()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-52c1dc6b2c1c> in <module>()
      1 df = fridge.load()
      2 
----> 3 df.head()

AttributeError: 'generator' object has no attribute 'head'

**Comment by lhx20070322** [comment]
when I run tests_on_large_datasets/redd_house3_f1_score.py

f1 = f1_score(disag_elec, elec)
 
raise ValueError('arrays must all be same length')

ValueError: arrays must all be same length

**Comment by PMeira** [comment]
@lhx20070322 Thanks for the report!

1. The `importlib_bootstrap.py` warnings are from upstream packages, not much we can do (besides forcibly ignoring them). I'll try to check how other projects are handling those.

2. The notebooks are updated yet, they're part of what I need to finish.

3. I'll check the `tests_on_large_datasets/redd_house3_f1_score.py`. It's most likely related to some of the API changes.

**Comment by PMeira** [comment]
Apparently the importlib warnings are related to Cython. The latest release seem to fix [the issue](https://github.com/cython/cython/issues/1720), but I imagine it will take some time for every dependency to update and recythonize their code.

About `tests_on_large_datasets/redd_house3_f1_score.py`, it's broken without my changes too. I'll try to find the last revision that worked and work from there.

**Comment by PMeira** [comment]
@oliparson @nipunbatra I think it's done now! I tested a lot more this time and fixed some issues that Pandas 0.22 caused. All nosetests, the `docs/` notebooks and `redd_house3_f1_score.py` run fine, both on Python 2.7 and 3.6.

One of the major changes that may still cause some trouble was the change in the resample method from Pandas. I wrote a (limited) wrapper function that may need some tweaking. Ideally we should rework the API to account for the change in Pandas, but I preferred to keep the changes local.
I also updated some of deprecated Pandas calls to hopefully make it easier to upgrade in the future.

I noticed pygraphviz doesn't work properly on Windows (issues with how it handles new-lines on node data), so I added a fallback to use one of the NetworkX's internal layout methods. 

Tested on Windows 10, Ubuntu 16.04 LTS and openSUSE Leap 42.3 (all 64-bit). Since the tests don't cover everything, there may be still little issues scattered around. 

@lhx20070322 If you want to give the new revision a try, it should work much better now.

**Comment by nipunbatra** [comment]
Wow @PMeira . This is excellent work. Keep it up! 
I just merged the change!

Paulo - do you know a simpler way of installing NILMTK than the current one? Like, it would be super awesome if we could just pip install nilmtk or conda install nilmtk. A good number of issues still revolve around installation.

@JackKelly, @oliparson : This is a day to celebrate. Very substantial contribution from the community :)

**Comment by oliparson** [comment]
Great work @PMeira! Awesome to see your hard work in the master branch :)

**Comment by PMeira** [comment]
Thanks, guys!

> Paulo - do you know a simpler way of installing NILMTK than the current one? Like, it would be super awesome if we could just pip install nilmtk or conda install nilmtk. A good number of issues still revolve around installation.

@nipunbatra I've actually been thinking a bit about this for one of my projects ([dss_python](https://github.com/PMeira/dss_python/), needs FreePascal and SuiteSparse to build from source, so it's a mess!). I think it's reasonable to create a Conda channel that includes all dependencies not readily available or, if possible, provide binary wheels directly via PyPI. The issue with PyPI is that the package owners of the dependencies would need to upload the wheels there; we could host the wheels somewhere else but that defeats the purpose. 

For NILMTK, a Conda channel seems better (`conda install -c nilmtk nilmtk`). I just noticed psycopg2 is already providing binary wheels on PyPI and it's also listed on Conda (even win64), so it seems only hmmlearn remains as troublesome (and maybe pygraphviz). I can give it a try later, but I still need to read more about Conda recipes and find what are their limitations.

**Comment by nipunbatra** [comment]
Thanks @PMeira 

Could you please pass me your contact information? Wanted to discuss some stuff offline.

**Comment by lhx20070322** [comment]
@PMeira I meet the same problem as  #647. Can you help me

**Comment by PMeira** [comment]
@lhx20070322 Until we fully investigate it, I added a temporary fix on #650

@nipunbatra I sent you a message on the email listed on your profile -- you can reach me at pmeira at ieee.org. As soon as I find time, I plan to read through the past issues to check if we need to fix anything else.

**Comment by lhx20070322** [comment]
@PMeira thank you! It is ok.

**Comment by metwebber** [comment]
Hi @PMeira , I have made f1_score and align_two_meters changes, but f1 = f1_score(disag_elec, test_elec) is  still not working for iawe dataset.

**Pull request merged**
